export const ADMIN_BOOKINGS_REQUEST = 'ADMIN_BOOKINGS_REQUEST'
export const ADMIN_BOOKINGS_SUCCESS = 'ADMIN_BOOKINGS_SUCCESS'
export const ADMIN_BOOKINGS_FAIL = 'ADMIN_BOOKINGS_FAIL'

export const ALL_BOOKINGS_REQUEST = 'ALL_BOOKINGS_REQUEST'
export const ALL_BOOKINGS_SUCCESS = 'ALL_BOOKINGS_SUCCESS'
export const ALL_BOOKINGS_FAIL = 'ALL_BOOKINGS_FAIL'

export const NEW_BOOKING_REQUEST = 'NEW_BOOKING_REQUEST'
export const NEW_BOOKING_SUCCESS = 'NEW_BOOKING_SUCCESS'
export const NEW_BOOKING_RESET = 'NEW_BOOKING_RESET'
export const NEW_BOOKING_FAIL = 'NEW_BOOKING_FAIL'

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_RESET = 'DELETE_BOOKING_RESET'
export const DELETE_BOOKING_FAIL = 'DELETE_BOOKING_FAIL'

export const UPDATE_BOOKING_REQUEST = 'UPDATE_BOOKING_REQUEST'
export const UPDATE_BOOKING_SUCCESS = 'UPDATE_BOOKING_SUCCESS'
export const UPDATE_BOOKING_RESET = 'UPDATE_BOOKING_RESET'
export const UPDATE_BOOKING_FAIL = 'UPDATE_BOOKING_FAIL'

export const BOOKING_DETAILS_REQUEST = 'BOOKING_DETAILS_REQUEST'
export const BOOKING_DETAILS_SUCCESS = 'BOOKING_DETAILS_SUCCESS'
export const BOOKING_DETAILS_FAIL = 'BOOKING_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const ALL_BOOKINGS_REQUESTPTSN = 'ALL_BOOKINGS_REQUESTPTSN'
export const ADMIN_BOOKINGS_REQUESTPTSN = 'ADMIN_BOOKINGS_REQUESTPTSN'
export const ALL_BOOKINGS_SUCCESSPTSN = 'ALL_BOOKINGS_SUCCESSPTSN'
export const ADMIN_BOOKINGS_SUCCESSPTSN = 'ADMIN_BOOKINGS_SUCCESSPTSN'
export const ALL_BOOKINGS_FAILPTSN = 'ALL_BOOKINGS_FAILPTSN'
export const ADMIN_BOOKINGS_FAILPTSN = 'ADMIN_BOOKINGS_FAILPTSN'
export const CLEAR_ERRORSPTSN = 'CLEAR_ERRORSPTSN'

export const BOOKING_DETAILS_REQUESTPTSN = 'BOOKING_DETAILS_REQUESTPTSN'
export const BOOKING_DETAILS_SUCCESSPTSN = 'BOOKING_DETAILS_SUCCESSPTSN'
export const BOOKING_DETAILS_FAILPTSN = 'BOOKING_DETAILS_FAILPTSN'

export const SEARCH_BOOKINGS_PTSN = 'SEARCH_BOOKINGS_PTSN'


export const NEW_DISCUSSIONCONTENT_REQUEST = 'NEW_DISCUSSIONCONTENT_REQUEST'
export const NEW_DISCUSSIONCONTENT_SUCCESS = 'NEW_DISCUSSIONCONTENT_SUCCESS'
export const NEW_DISCUSSIONCONTENT_RESET = 'NEW_DISCUSSIONCONTENT_RESET'
export const NEW_DISCUSSIONCONTENT_FAIL = 'NEW_DISCUSSIONCONTENT_FAIL'

export const ADMIN_DISCUSSIONCONTENTS_REQUEST = 'ADMIN_DISCUSSIONCONTENTS_REQUEST'
export const ADMIN_DISCUSSIONCONTENTS_SUCCESS = 'ADMIN_DISCUSSIONCONTENTS_SUCCESS'
export const ADMIN_DISCUSSIONCONTENTS_FAIL = 'ADMIN_DISCUSSIONCONTENTS_FAIL'

export const UPDATE_DISCUSSIONCONTENT_REQUEST = 'UPDATE_DISCUSSIONCONTENT_REQUEST'
export const UPDATE_DISCUSSIONCONTENT_SUCCESS = 'UPDATE_DISCUSSIONCONTENT_SUCCESS'
export const UPDATE_DISCUSSIONCONTENT_RESET = 'UPDATE_DISCUSSIONCONTENT_RESET'
export const UPDATE_DISCUSSIONCONTENT_FAIL = 'UPDATE_DISCUSSIONCONTENT_FAIL'

export const DELETE_DISCUSSIONCONTENT_REQUEST = 'DELETE_DISCUSSIONCONTENT_REQUEST'
export const DELETE_DISCUSSIONCONTENT_SUCCESS = 'DELETE_DISCUSSIONCONTENT_SUCCESS'
export const DELETE_DISCUSSIONCONTENT_RESET = 'DELETE_DISCUSSIONCONTENT_RESET'
export const DELETE_DISCUSSIONCONTENT_FAIL = 'DELETE_DISCUSSIONCONTENT_FAIL'


export const NEW_DISCUSSIONTIME_REQUEST = 'NEW_DISCUSSIONTIME_REQUEST'
export const NEW_DISCUSSIONTIME_SUCCESS = 'NEW_DISCUSSIONTIME_SUCCESS'
export const NEW_DISCUSSIONTIME_RESET = 'NEW_DISCUSSIONTIME_RESET'
export const NEW_DISCUSSIONTIME_FAIL = 'NEW_DISCUSSIONTIME_FAIL'

export const ADMIN_DISCUSSIONTIMES_REQUEST = 'ADMIN_DISCUSSIONTIMES_REQUEST'
export const ADMIN_DISCUSSIONTIMES_SUCCESS = 'ADMIN_DISCUSSIONTIMES_SUCCESS'
export const ADMIN_DISCUSSIONTIMES_FAIL = 'ADMIN_DISCUSSIONTIMES_FAIL'

export const UPDATE_DISCUSSIONTIME_REQUEST = 'UPDATE_DISCUSSIONTIME_REQUEST'
export const UPDATE_DISCUSSIONTIME_SUCCESS = 'UPDATE_DISCUSSIONTIME_SUCCESS'
export const UPDATE_DISCUSSIONTIME_RESET = 'UPDATE_DISCUSSIONTIME_RESET'
export const UPDATE_DISCUSSIONTIME_FAIL = 'UPDATE_DISCUSSIONTIME_FAIL'

export const DELETE_DISCUSSIONTIME_REQUEST = 'DELETE_DISCUSSIONTIME_REQUEST'
export const DELETE_DISCUSSIONTIME_SUCCESS = 'DELETE_DISCUSSIONTIME_SUCCESS'
export const DELETE_DISCUSSIONTIME_RESET = 'DELETE_DISCUSSIONTIME_RESET'
export const DELETE_DISCUSSIONTIME_FAIL = 'DELETE_DISCUSSIONTIME_FAIL'

