export const ADMIN_CONTENTS_REQUEST = 'ADMIN_CONTENTS_REQUEST'
export const ADMIN_CONTENTS_SUCCESS = 'ADMIN_CONTENTS_SUCCESS'
export const ADMIN_CONTENTS_FAIL = 'ADMIN_CONTENTS_FAIL'

export const ALL_CONTENTS_REQUEST = 'ALL_CONTENTS_REQUEST'
export const ALL_CONTENTS_SUCCESS = 'ALL_CONTENTS_SUCCESS'
export const ALL_CONTENTS_FAIL = 'ALL_CONTENTS_FAIL'

export const NEW_CONTENT_REQUEST = 'NEW_CONTENT_REQUEST'
export const NEW_CONTENT_SUCCESS = 'NEW_CONTENT_SUCCESS'
export const NEW_CONTENT_RESET = 'NEW_CONTENT_RESET'
export const NEW_CONTENT_FAIL = 'NEW_CONTENT_FAIL'

export const DELETE_CONTENT_REQUEST = 'DELETE_CONTENT_REQUEST'
export const DELETE_CONTENT_SUCCESS = 'DELETE_CONTENT_SUCCESS'
export const DELETE_CONTENT_RESET = 'DELETE_CONTENT_RESET'
export const DELETE_CONTENT_FAIL = 'DELETE_CONTENT_FAIL'

export const UPDATE_CONTENT_REQUEST = 'UPDATE_CONTENT_REQUEST'
export const UPDATE_CONTENT_SUCCESS = 'UPDATE_CONTENT_SUCCESS'
export const UPDATE_CONTENT_RESET = 'UPDATE_CONTENT_RESET'
export const UPDATE_CONTENT_FAIL = 'UPDATE_CONTENT_FAIL'

export const CONTENT_DETAILS_REQUEST = 'CONTENT_DETAILS_REQUEST'
export const CONTENT_DETAILS_SUCCESS = 'CONTENT_DETAILS_SUCCESS'
export const CONTENT_DETAILS_FAIL = 'CONTENT_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const ALL_CONTENTS_REQUESTPTSN = 'ALL_CONTENTS_REQUESTPTSN'
export const ADMIN_CONTENTS_REQUESTPTSN = 'ADMIN_CONTENTS_REQUESTPTSN'
export const ALL_CONTENTS_SUCCESSPTSN = 'ALL_CONTENTS_SUCCESSPTSN'
export const ADMIN_CONTENTS_SUCCESSPTSN = 'ADMIN_CONTENTS_SUCCESSPTSN'
export const ALL_CONTENTS_FAILPTSN = 'ALL_CONTENTS_FAILPTSN'
export const ADMIN_CONTENTS_FAILPTSN = 'ADMIN_CONTENTS_FAILPTSN'
export const CLEAR_ERRORSPTSN = 'CLEAR_ERRORSPTSN'

export const CONTENT_DETAILS_REQUESTPTSN = 'CONTENT_DETAILS_REQUESTPTSN'
export const CONTENT_DETAILS_SUCCESSPTSN = 'CONTENT_DETAILS_SUCCESSPTSN'
export const CONTENT_DETAILS_FAILPTSN = 'CONTENT_DETAILS_FAILPTSN'